// @vitest-environment node

import { strFromU8, strToU8, unzipSync, zipSync } from "fflate";
import { describe, expect, it } from "vitest";
import { ImportError } from "../source.ts";
import { MAX_ENTRY_BYTES, readPptx } from "./pptx.ts";

/**
 * Tiny decks generated by the test, never a real book's lyrics (SDD-0003 §6).
 * Only the parts the reader uses: presentation, rels, slides, one layout, one
 * master and its theme.
 */
const NS =
  'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' +
  'xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" ' +
  'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"';
const REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";

const rels = (items: [string, string, string][]) =>
  `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${items
    .map(
      ([id, type, target]) => `<Relationship Id="${id}" Type="${REL}/${type}" Target="${target}"/>`,
    )
    .join("")}</Relationships>`;

const frame = (x: number, y: number, w: number, h = 1000000) =>
  `<a:xfrm><a:off x="${x * 12700}" y="${y * 12700}"/><a:ext cx="${w * 12700}" cy="${h}"/></a:xfrm>`;

const run = (text: string, attrs = "", extra = "") =>
  `<a:r><a:rPr lang="en" ${attrs}>${extra}</a:rPr><a:t>${text}</a:t></a:r>`;

const shape = (inner: string, xfrm = frame(100, 50, 400), nv = "", pr = "<a:bodyPr/>") =>
  `<p:sp><p:nvSpPr><p:cNvPr id="2" name="s"/><p:cNvSpPr/><p:nvPr>${nv}</p:nvPr></p:nvSpPr>` +
  `<p:spPr>${xfrm}</p:spPr><p:txBody>${pr}<a:lstStyle/>${inner}</p:txBody></p:sp>`;

const tree = (inner: string) =>
  `<?xml version="1.0"?><p:sld ${NS}><p:cSld><p:spTree>${inner}</p:spTree></p:cSld></p:sld>`;

interface Deck {
  /** Slide XML by file name; the presentation lists them in `order`. */
  slides: Record<string, string>;
  order: string[];
  layout?: string;
  master?: string;
  theme?: string;
  /** Attributes added to the presentation's root, e.g. a renamed namespace. */
  rootAttrs?: string;
}

function deck({ slides, order, layout, master, theme }: Deck): Uint8Array {
  const files: Record<string, string> = {
    "ppt/presentation.xml": `<?xml version="1.0"?><p:presentation ${NS}><p:sldMasterIdLst/><p:sldIdLst>${order
      .map((_, i) => `<p:sldId id="${256 + i}" r:id="rId${10 + i}"/>`)
      .join("")}</p:sldIdLst><p:sldSz cx="${720 * 12700}" cy="${540 * 12700}"/></p:presentation>`,
    "ppt/_rels/presentation.xml.rels": rels(
      order.map((name, i) => [`rId${10 + i}`, "slide", `slides/${name}`]),
    ),
    "ppt/slideLayouts/slideLayout1.xml": `<?xml version="1.0"?><p:sldLayout ${NS}><p:cSld><p:spTree>${layout ?? ""}</p:spTree></p:cSld></p:sldLayout>`,
    "ppt/slideLayouts/_rels/slideLayout1.xml.rels": rels([
      ["rId1", "slideMaster", "../slideMasters/slideMaster1.xml"],
    ]),
    "ppt/slideMasters/slideMaster1.xml": `<?xml version="1.0"?><p:sldMaster ${NS}><p:cSld><p:spTree>${master ?? ""}</p:spTree></p:cSld><p:txStyles><p:titleStyle><a:lvl1pPr><a:defRPr sz="3200"><a:latin typeface="+mj-lt"/></a:defRPr></a:lvl1pPr></p:titleStyle><p:bodyStyle><a:lvl1pPr><a:defRPr sz="2400"><a:latin typeface="+mn-lt"/></a:defRPr></a:lvl1pPr></p:bodyStyle></p:txStyles></p:sldMaster>`,
    "ppt/slideMasters/_rels/slideMaster1.xml.rels": rels([
      ["rId1", "theme", "../theme/theme1.xml"],
    ]),
    "ppt/theme/theme1.xml":
      theme ??
      `<?xml version="1.0"?><a:theme ${NS}><a:themeElements><a:fontScheme name="t"><a:majorFont><a:latin typeface="Major Face"/></a:majorFont><a:minorFont><a:latin typeface="Minor Face"/></a:minorFont></a:fontScheme></a:themeElements></a:theme>`,
  };
  for (const [name, xml] of Object.entries(slides)) {
    files[`ppt/slides/${name}`] = xml;
    files[`ppt/slides/_rels/${name}.rels`] = rels([
      ["rId1", "slideLayout", "../slideLayouts/slideLayout1.xml"],
    ]);
  }
  return zipSync(Object.fromEntries(Object.entries(files).map(([k, v]) => [k, strToU8(v)])));
}

const para = (...runs: string[]) => `<a:p>${runs.join("")}</a:p>`;
const lines = (pages: ReturnType<typeof readPptx>, i = 0) => pages[i].lines.map((l) => l.text);

describe("readPptx", () => {
  it("orders slides by the presentation's rels, not by file name", () => {
    const pages = readPptx(
      deck({
        slides: {
          "slide1.xml": tree(shape(para(run("Third", 'sz="2000"')))),
          "slide2.xml": tree(shape(para(run("First", 'sz="2000"')))),
          "slide3.xml": tree(shape(para(run("Second", 'sz="2000"')))),
        },
        order: ["slide2.xml", "slide3.xml", "slide1.xml"],
      }),
    );
    expect(pages.map((p) => p.number)).toEqual([1, 2, 3]);
    expect(pages.map((p) => p.lines[0].text)).toEqual(["First", "Second", "Third"]);
    expect(pages[0]).toMatchObject({ width: 720, height: 540 });
  });

  it("takes x from the shape and its indent, and size and font from the run", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              `<a:p><a:pPr marL="127000"/>${run("Line one", 'sz="2000"', '<a:latin typeface="Own Face"/>')}</a:p>`,
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    // 100 pt + the default 7.2 pt inset + a 10 pt margin.
    expect(page.lines[0]).toMatchObject({ x: 117.2, size: 20, font: "Own Face" });
  });

  it("inherits size and font from the layout, then the master, then txStyles", () => {
    const ph = (type: string, idx: number, size = "", font = "", y = 60) =>
      `<p:sp><p:nvSpPr><p:cNvPr id="3" name="ph"/><p:cNvSpPr/><p:nvPr><p:ph type="${type}" idx="${idx}"/></p:nvPr></p:nvSpPr><p:spPr>${frame(40, y, 300)}</p:spPr><p:txBody><a:bodyPr/><a:lstStyle>${
        size ? `<a:lvl1pPr><a:defRPr sz="${size}">${font}</a:defRPr></a:lvl1pPr>` : ""
      }</a:lstStyle></p:txBody></p:sp>`;
    const slideShape = (type: string, idx: number, text: string) =>
      `<p:sp><p:nvSpPr><p:cNvPr id="2" name="s"/><p:cNvSpPr/><p:nvPr><p:ph type="${type}" idx="${idx}"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/>${para(run(text))}</p:txBody></p:sp>`;

    const [page] = readPptx(
      deck({
        // The layout sets the body's size; the master the title's frame.
        layout:
          ph("body", 1, "2800", '<a:latin typeface="Layout Face"/>') + ph("title", 0, "", "", 300),
        master: ph("title", 0, "", "", 300),
        slides: {
          "s.xml": tree(slideShape("body", 1, "Body text") + slideShape("title", 0, "Title text")),
        },
        order: ["s.xml"],
      }),
    );
    const byText = (text: string) => page.lines.find((l) => l.text === text);
    expect(byText("Body text")).toMatchObject({ size: 28, font: "Layout Face", x: 47.2 });
    // No size in layout or master placeholders: txStyles' titleStyle, and the
    // theme's major font.
    expect(byText("Title text")).toMatchObject({ size: 32, font: "Major Face" });
    expect(byText("Title text")?.x).toBe(47.2);
  });

  it("falls back to 18 pt and the theme's minor font for loose text", () => {
    const [page] = readPptx(
      deck({ slides: { "s.xml": tree(shape(para(run("Plain")))) }, order: ["s.xml"] }),
    );
    expect(page.lines[0]).toMatchObject({ size: 18, font: "Minor Face" });
  });

  it("resolves +mn-lt and +mj-lt through the theme", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              para(run("Minor", 'sz="2000"', '<a:latin typeface="+mn-lt"/>')) +
                para(run("Major", 'sz="2000"', '<a:latin typeface="+mj-lt"/>')),
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(page.lines.map((l) => l.font)).toEqual(["Minor Face", "Major Face"]);
  });

  it("gives ascending y to paragraphs and line breaks, and joins fields", () => {
    const br = '<a:br><a:rPr sz="2000"/></a:br>';
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              para(run("Line one", 'sz="2000"'), br, run("Line two", 'sz="2000"')) +
                para(run("Line three", 'sz="2000"')) +
                `<a:p><a:fld id="{1}" type="slidenum"><a:rPr sz="2000"/><a:t>7</a:t></a:fld></a:p>`,
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(lines([page])).toEqual(["Line one", "Line two", "Line three", "7"]);
    const ys = page.lines.map((l) => l.y);
    expect(ys[0]).toBeCloseTo(50 + 3.6 + 0.8 * 20, 5);
    expect(ys[1] - ys[0]).toBeCloseTo(24, 5);
    expect(ys).toEqual([...ys].sort((a, b) => a - b));
    expect(new Set(ys).size).toBe(4);
  });

  it("applies a line spacing percentage", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              `<a:p><a:pPr><a:lnSpc><a:spcPct val="50000"/></a:lnSpc></a:pPr>${run("One", 'sz="2000"')}</a:p>` +
                `<a:p><a:pPr><a:lnSpc><a:spcPct val="50000"/></a:lnSpc></a:pPr>${run("Two", 'sz="2000"')}</a:p>`,
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(page.lines[1].y - page.lines[0].y).toBeCloseTo(12, 5);
  });

  it("applies a group's transform to the shapes inside it", () => {
    const group = (inner: string) =>
      `<p:grpSp><p:nvGrpSpPr><p:cNvPr id="9" name="g"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="${200 * 12700}" y="${100 * 12700}"/><a:ext cx="${400 * 12700}" cy="${200 * 12700}"/><a:chOff x="${10 * 12700}" y="${20 * 12700}"/><a:chExt cx="${200 * 12700}" cy="${100 * 12700}"/></a:xfrm></p:grpSpPr>${inner}</p:grpSp>`;
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            group(shape(para(run("Inside", 'sz="2000"')), frame(30, 40, 100))) +
              shape(para(run("Outside", 'sz="2000"')), frame(30, 40, 100)),
          ),
        },
        order: ["s.xml"],
      }),
    );
    const inside = page.lines.find((l) => l.text === "Inside");
    const outside = page.lines.find((l) => l.text === "Outside");
    // Scale 2: child (30, 40) → 200 + (30 - 10) * 2 = 240, 100 + (40 - 20) * 2 = 140.
    expect(inside?.x).toBeCloseTo(240 + 7.2 * 2, 5);
    expect(inside?.y).toBeCloseTo(140 + 3.6 * 2 + 16, 5);
    expect(outside?.x).toBeCloseTo(37.2, 5);
  });

  it("puts shapes side by side on one line, left to right", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(para(run("12", 'sz="2000"')), frame(20, 50, 40)) +
              shape(para(run("Title here", 'sz="2000"')), frame(80, 50, 300)),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(lines([page])).toEqual(["12 Title here"]);
  });

  it("keeps whitespace-only runs, so words don't glue together", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(para(run("Glory", 'sz="2000"'), run(" ", 'sz="2000"'), run("be", 'sz="2000"'))),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(lines([page])).toEqual(["Glory be"]);
  });

  it("takes a multi-run line's size and font from its first real run", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              para(
                run(" ", 'sz="1000"'),
                run("Mixed", 'sz="2000"', '<a:latin typeface="First Face"/>'),
                run(" line", 'sz="1600"', '<a:latin typeface="Other Face"/>'),
              ),
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(page.lines).toHaveLength(1);
    expect(page.lines[0]).toMatchObject({ text: "Mixed line", size: 20, font: "First Face" });
  });

  it("names a bold or italic face as a PDF does", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              para(run("Plain", 'sz="2000"', '<a:latin typeface="Face"/>')) +
                para(run("Bold", 'sz="2000" b="1"', '<a:latin typeface="Face"/>')) +
                para(run("Italic", 'sz="2000" i="1"', '<a:latin typeface="Face"/>')) +
                para(run("Both", 'sz="2000" b="1" i="1"', '<a:latin typeface="Face"/>')),
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(page.lines.map((l) => l.font)).toEqual([
      "Face",
      "Face-Bold",
      "Face-Italic",
      "Face-BoldItalic",
    ]);
  });

  it("merges side-by-side shapes of unequal sizes on one line", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(para(run("7", 'sz="2000"')), frame(20, 50, 40)) +
              shape(para(run("A title", 'sz="2800"')), frame(80, 50, 300)),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(lines([page])).toEqual(["7 A title"]);
  });

  it("honours vertical anchoring", () => {
    const at = (anchor: string) =>
      readPptx(
        deck({
          slides: {
            "s.xml": tree(
              shape(
                para(run("Line", 'sz="2000"')),
                frame(10, 100, 200, 100 * 12700),
                "",
                `<a:bodyPr anchor="${anchor}"/>`,
              ),
            ),
          },
          order: ["s.xml"],
        }),
      )[0].lines[0].y;
    // A 100 pt box with 3.6 pt insets and one 24 pt line.
    expect(at("t")).toBeCloseTo(100 + 3.6 + 16, 5);
    expect(at("ctr")).toBeCloseTo(100 + 3.6 + (100 - 7.2 - 24) / 2 + 16, 5);
    expect(at("b")).toBeCloseTo(100 + 3.6 + (100 - 7.2 - 24) + 16, 5);
  });

  it("scales sizes by normAutofit's fontScale", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              para(run("Scaled", 'sz="2000"')),
              frame(100, 50, 400),
              "",
              '<a:bodyPr><a:normAutofit fontScale="85000"/></a:bodyPr>',
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(page.lines[0].size).toBeCloseTo(17, 5);
  });

  it("uses spcPts line spacing, and an empty paragraph still takes a line", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              `<a:p><a:pPr><a:lnSpc><a:spcPts val="3000"/></a:lnSpc></a:pPr>${run("One", 'sz="2000"')}</a:p>` +
                '<a:p><a:endParaRPr sz="2000"/></a:p>' +
                `<a:p><a:pPr><a:lnSpc><a:spcPts val="3000"/></a:lnSpc></a:pPr>${run("Two", 'sz="2000"')}</a:p>`,
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(lines([page])).toEqual(["One", "Two"]);
    // 30 pt, then an empty 24 pt line, then 30 pt.
    expect(page.lines[1].y - page.lines[0].y).toBeCloseTo(54, 5);
  });

  it("matches a placeholder by idx before type", () => {
    const ph = (idx: number, size: number, y: number) =>
      `<p:sp><p:nvSpPr><p:cNvPr id="3" name="ph"/><p:cNvSpPr/><p:nvPr><p:ph type="body" idx="${idx}"/></p:nvPr></p:nvSpPr><p:spPr>${frame(40, y, 300)}</p:spPr><p:txBody><a:bodyPr/><a:lstStyle><a:lvl1pPr><a:defRPr sz="${size}"/></a:lvl1pPr></a:lstStyle></p:txBody></p:sp>`;
    const slideShape = `<p:sp><p:nvSpPr><p:cNvPr id="2" name="s"/><p:cNvSpPr/><p:nvPr><p:ph type="body" idx="2"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/>${para(run("Second"))}</p:txBody></p:sp>`;
    const [page] = readPptx(
      deck({
        layout: ph(1, 3000, 10) + ph(2, 2000, 200),
        slides: { "s.xml": tree(slideShape) },
        order: ["s.xml"],
      }),
    );
    expect(page.lines[0].size).toBe(20);
    expect(page.lines[0].y).toBeCloseTo(200 + 3.6 + 16, 5);
  });

  it("skips slide number, date and footer placeholders", () => {
    const furniture = (type: string) =>
      `<p:sp><p:nvSpPr><p:cNvPr id="4" name="f"/><p:cNvSpPr/><p:nvPr><p:ph type="${type}"/></p:nvPr></p:nvSpPr><p:spPr>${frame(10, 500, 100)}</p:spPr><p:txBody><a:bodyPr/><a:lstStyle/>${para(run("Footer text"))}</p:txBody></p:sp>`;
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(para(run("Song"))) + furniture("sldNum") + furniture("dt") + furniture("ftr"),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(lines([page])).toEqual(["Song"]);
  });

  it("composes nested groups", () => {
    const group = (x: number, y: number, inner: string) =>
      `<p:grpSp><p:nvGrpSpPr><p:cNvPr id="9" name="g"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="${x * 12700}" y="${y * 12700}"/><a:ext cx="${200 * 12700}" cy="${200 * 12700}"/><a:chOff x="0" y="0"/><a:chExt cx="${100 * 12700}" cy="${100 * 12700}"/></a:xfrm></p:grpSpPr>${inner}</p:grpSp>`;
    const [page] = readPptx(
      deck({
        // Inner scale 2, outer scale 2: a child at 10 lands at 100 + 2 * (20 + 2 * 10).
        slides: {
          "s.xml": tree(
            group(100, 100, group(20, 20, shape(para(run("Deep")), frame(10, 10, 50)))),
          ),
        },
        order: ["s.xml"],
      }),
    );
    // x: outer 100 + 2 * (inner 20 + 2 * 10) + inset 7.2 * 4.
    expect(page.lines[0].x).toBeCloseTo(100 + 2 * (20 + 2 * 10) + 7.2 * 4, 5);
  });

  it("decodes entities and Office escapes, and keeps spaces", () => {
    const [page] = readPptx(
      deck({
        slides: {
          "s.xml": tree(
            shape(
              '<a:p><a:r><a:t xml:space="preserve">Tom &amp; Jerry &#233; &#x41;_x0042_</a:t></a:r></a:p>',
            ),
          ),
        },
        order: ["s.xml"],
      }),
    );
    expect(page.lines[0].text).toBe("Tom & Jerry é AB");
  });

  it("reads table cells in row order", () => {
    const cell = (text: string) =>
      `<a:tc><a:txBody><a:bodyPr/><a:lstStyle/>${para(run(text, 'sz="2000"'))}</a:txBody><a:tcPr/></a:tc>`;
    const table = `<p:graphicFrame><p:nvGraphicFramePr><p:cNvPr id="5" name="t"/><p:cNvGraphicFramePr/><p:nvPr/></p:nvGraphicFramePr><p:xfrm><a:off x="${50 * 12700}" y="${100 * 12700}"/><a:ext cx="${400 * 12700}" cy="${100 * 12700}"/></p:xfrm><a:graphic><a:graphicData uri="t"><a:tbl><a:tblGrid><a:gridCol w="${100 * 12700}"/><a:gridCol w="${300 * 12700}"/></a:tblGrid><a:tr h="${40 * 12700}">${cell("1")}${cell("First row")}</a:tr><a:tr h="${40 * 12700}">${cell("2")}${cell("Second row")}</a:tr></a:tbl></a:graphicData></a:graphic></p:graphicFrame>`;
    const [page] = readPptx(deck({ slides: { "s.xml": tree(table) }, order: ["s.xml"] }));
    expect(lines([page])).toEqual(["1 First row", "2 Second row"]);
  });

  it("reads mc:AlternateContent's choice, else its fallback", () => {
    const mc = `<mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"><mc:Choice Requires="x">${shape(para(run("Chosen")))}</mc:Choice><mc:Fallback>${shape(para(run("Fell back")))}</mc:Fallback></mc:AlternateContent>`;
    const onlyFallback = `<mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"><mc:Fallback>${shape(para(run("Fell back")))}</mc:Fallback></mc:AlternateContent>`;
    const pages = readPptx(
      deck({
        slides: { "a.xml": tree(mc), "b.xml": tree(onlyFallback) },
        order: ["a.xml", "b.xml"],
      }),
    );
    expect(pages.map((p) => p.lines[0].text)).toEqual(["Chosen", "Fell back"]);
  });

  it("skips a hidden slide, and the others keep their numbers", () => {
    const hidden = tree(shape(para(run("Hidden")))).replace("<p:sld ", '<p:sld show="0" ');
    const pages = readPptx(
      deck({
        slides: {
          "a.xml": tree(shape(para(run("A")))),
          "b.xml": hidden,
          "c.xml": tree(shape(para(run("C")))),
        },
        order: ["a.xml", "b.xml", "c.xml"],
      }),
    );
    expect(pages.map((p) => [p.number, p.lines[0].text])).toEqual([
      [1, "A"],
      [3, "C"],
    ]);
  });

  it("finds slide ids through a renamed relationships prefix", () => {
    const data = deck({
      slides: { "a.xml": tree(shape(para(run("A")))) },
      order: ["a.xml"],
      rootAttrs: "",
    });
    const files = unzipSync(data);
    const xml = strFromU8(files["ppt/presentation.xml"])
      .replace("xmlns:r=", "xmlns:rel=")
      .replace("r:id=", "rel:id=");
    files["ppt/presentation.xml"] = strToU8(xml);
    expect(readPptx(zipSync(files))[0].lines[0].text).toBe("A");
  });

  it("refuses a slide whose relationship is missing", () => {
    const files = unzipSync(deck({ slides: { "a.xml": tree("") }, order: ["a.xml"] }));
    files["ppt/_rels/presentation.xml.rels"] = strToU8(rels([]));
    expect(() => readPptx(zipSync(files))).toThrow(/Slide 1.*rId10/);
  });

  it("refuses malformed XML, naming the part", () => {
    const bad = "<p:sld><p:cSld></p:sld>";
    expect(() => readPptx(deck({ slides: { "a.xml": bad }, order: ["a.xml"] }))).toThrow(
      /ppt\/slides\/a\.xml/,
    );
  });

  it("refuses an entry that unzips past the cap", () => {
    // A small cap and an entry just over it: the check is the same, and fast.
    const cap = 1024 * 1024;
    const zip = zipSync({ "ppt/presentation.xml": new Uint8Array(cap + 1) });
    expect(() => readPptx(zip, { maxEntryBytes: cap })).toThrow(/1 MB/);
  });

  it("caps an entry at 50 MB by default", () => {
    expect(MAX_ENTRY_BYTES).toBe(50 * 1024 * 1024);
  });

  it("reads a page range", () => {
    const slides = Object.fromEntries(
      [1, 2, 3, 4].map((n) => [`s${n}.xml`, tree(shape(para(run(`Slide ${n}`))))]),
    );
    const data = deck({ slides, order: ["s1.xml", "s2.xml", "s3.xml", "s4.xml"] });
    expect(readPptx(data, { from: 2, to: 3 }).map((p) => [p.number, p.lines[0].text])).toEqual([
      [2, "Slide 2"],
      [3, "Slide 3"],
    ]);
    expect(readPptx(data, { from: 4 })).toHaveLength(1);
  });

  it("returns an empty page for a slide with no text", () => {
    const [page] = readPptx(deck({ slides: { "s.xml": tree("") }, order: ["s.xml"] }));
    expect(page.lines).toEqual([]);
  });

  it("refuses a file that is not a zip", () => {
    expect(() => readPptx(strToU8("%PDF-1.7 not a deck"))).toThrow(ImportError);
    expect(() => readPptx(strToU8("%PDF-1.7 not a deck"))).toThrow(/zip/);
  });

  it("refuses a zip without a presentation", () => {
    const zip = zipSync({ "hello.txt": strToU8("hi") });
    expect(() => readPptx(zip)).toThrow(/ppt\/presentation\.xml/);
  });
});
